# -*- coding: utf-8 -*-
"""embeddings-agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VMo_mPZAsCFNIqAK1kNSSbqGZXt3pjLK
"""

!git clone https://github.com/ksnpavankumar/Ragcodebase.git

pwd

# Commented out IPython magic to ensure Python compatibility.
# %pip install azure-core azure-search-documents openai

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q fastapi "uvicorn[standard]" pyngrok nest-asyncio

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q openai azure-search-documents azure-search-documents-indexes pypdf pandas python-docx openpyxl tiktoken

import os
import threading
import nest_asyncio
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from pyngrok import ngrok
import uvicorn

from azure.core.credentials import AzureKeyCredential
from azure.search.documents import SearchClient
from azure.search.documents.models import VectorizedQuery
from google.colab import userdata
from openai import OpenAI

# ==========================================
# 0. CONFIGURATION & CLIENT INITIALIZATION
# ==========================================
EMBEDDING_DEPLOYMENT_NAME = "text-embedding-3-small"
LLM_DEPLOYMENT_NAME = "gpt-5-mini"
INDEX_NAME = "enterprise-knowledge-index"

SEARCH_ENDPOINT = "https://search-rag-knowledge.search.windows.net"
SEARCH_API_KEY = userdata.get("search_api_key")

AZURE_API_KEY = userdata.get("AZURE_API_KEY")
AZURE_ENDPOINT = userdata.get("AZURE_ENDPOINT")

# Initialize Clients
openai_client = OpenAI(api_key=AZURE_API_KEY, base_url=AZURE_ENDPOINT)

search_client = SearchClient(
    endpoint=SEARCH_ENDPOINT,
    index_name=INDEX_NAME,
    credential=AzureKeyCredential(SEARCH_API_KEY),
)

# Initialize FastAPI App
app = FastAPI(title="Enterprise Engineering Knowledge Copilot API")

# Define Request Schema using Pydantic
class QueryRequest(BaseModel):
    question: str

@app.get("/")
def home():
    return {"status": "Enterprise Engineering Knowledge Copilot API is running!"}

@app.post("/query")
def run_copilot(req: QueryRequest):
    try:
        user_question = req.question

        # ==========================================
        # 1. RETRIEVAL PHASE (Vector Search)
        # ==========================================
        # A. Convert user question into a vector using Azure AI Foundry
        embedding_response = openai_client.embeddings.create(
            input=[user_question], model=EMBEDDING_DEPLOYMENT_NAME, dimensions=1536
        )
        query_vector = embedding_response.data[0].embedding

        # B. Construct vector search query with corrected parameter name
        vector_query = VectorizedQuery(
            vector=query_vector, k_nearest_neighbors=3, fields="contentVector"
        )

        # C. Execute search against Azure AI Search
        search_results = search_client.search(
            search_text=None,
            vector_queries=[vector_query],
            select=[
                "chunk_id",
                "source_file",
                "source_type",
                "page_number",
                "linked_keys",
                "content",
            ],
        )

        # D. Collect and format retrieved context chunks
        retrieved_chunks = []
        context_snippets = []
        sources_used = []

        for idx, result in enumerate(search_results, start=1):
            chunk_data = {
                "id": result["chunk_id"],
                "source": result["source_file"],
                "type": result["source_type"],
                "page": result["page_number"],
                "jira_links": result["linked_keys"],
                "content": result["content"],
            }
            retrieved_chunks.append(chunk_data)
            sources_used.append({
                "file": result["source_file"],
                "type": result["source_type"],
                "jira_links": result["linked_keys"]
            })
            context_snippets.append(
                f"--- Source [{idx}]: {result['source_file']} (Type:"
                f" {result['source_type']}) ---\n{result['content']}"
            )

        combined_context = "\n\n".join(context_snippets)

        # ==========================================
        # 2. GENERATION PHASE (Agent via gpt-5-mini)
        # ==========================================
        response = openai_client.chat.completions.create(
            model=LLM_DEPLOYMENT_NAME,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an expert Enterprise Engineering Knowledge Copilot"
                        " agent. Your job is to answer user engineering and banking"
                        " policy questions accurately using ONLY the provided enterprise"
                        " context (Jira, Confluence, and Banking PDFs). Always"
                        " explicitly cite your sources, file names, and cross-linked"
                        " Jira ticket IDs in your response."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"Context Documents:\n{combined_context}\n\nUser Question:"
                        f" {user_question}"
                    ),
                },
            ],
            temperature=1,
        )

        answer = response.choices[0].message.content

        return {
            "question": user_question,
            "answer": answer,
            "retrieved_chunks_count": len(retrieved_chunks),
            "sources": sources_used
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ==========================================
# 3. RUN SERVER & EXPOSE NGROK TUNNEL
# ==========================================
# Ensure required packages are installed if running in Colab
# %pip install -q fastapi "uvicorn[standard]" pyngrok nest-asyncio

nest_asyncio.apply()

def run_server():
    uvicorn.run(app, host="0.0.0.0", port=8000)

# Start Uvicorn in a background thread so it doesn't block the notebook
threading.Thread(target=run_server, daemon=True).start()

# Establish ngrok public tunnel
ngrok_token = userdata.get("NGROK")
ngrok.set_auth_token(ngrok_token)
public_url = ngrok.connect(8000).public_url
print("\n" + "=" * 60)
print(f"🚀 FastAPI Copilot Live!")
print(f"📄 Interactive Swagger Docs: {public_url}/docs")
print(f"🌐 Public API Endpoint:     {public_url}/query")
print("=" * 60)

# Commented out IPython magic to ensure Python compatibility.

# %cd Ragcodebase/

!git status

!git config --global user.email "kunasanipavan@gmail.com"
!git config --global user.name "pavan kunasani"

!git add .
!git commit -m "Update FastAPI implementation"

!git push