# -*- coding: utf-8 -*-
"""embeddings-agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VMo_mPZAsCFNIqAK1kNSSbqGZXt3pjLK
"""

!git clone https://github.com/ksnpavankumar/Ragcodebase.git

pwd

# Commented out IPython magic to ensure Python compatibility.
# %pip install azure-core azure-search-documents openai

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q fastapi "uvicorn[standard]" pyngrok nest-asyncio

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q openai azure-search-documents azure-search-documents-indexes pypdf pandas python-docx openpyxl tiktoken

import os
import threading
import json
import httpx
import nest_asyncio
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from pyngrok import ngrok
import uvicorn

from azure.core.credentials import AzureKeyCredential
from azure.search.documents import SearchClient
from azure.search.documents.models import VectorizedQuery
from google.colab import userdata
from openai import OpenAI

# ==========================================
# 0. CONFIGURATION & CLIENT INITIALIZATION
# ==========================================
EMBEDDING_DEPLOYMENT_NAME = "text-embedding-3-small"
LLM_DEPLOYMENT_NAME = "gpt-5-mini"
INDEX_NAME = "enterprise-knowledge-index"

SEARCH_ENDPOINT = "https://search-rag-knowledge.search.windows.net"
SEARCH_API_KEY = userdata.get("search_api_key")

AZURE_API_KEY = userdata.get("AZURE_API_KEY")
AZURE_ENDPOINT = userdata.get("AZURE_ENDPOINT")

# Atlassian / Jira Credentials from Colab Secrets
ATLASSIAN_DOMAIN = userdata.get("ATLASSIAN_DOMAIN")  # e.g., "your-team.atlassian.net"
ATLASSIAN_EMAIL = userdata.get("ATLASSIAN_EMAIL")
ATLASSIAN_API_TOKEN = userdata.get("ATLASSIAN_API_TOKEN")

# Initialize Azure OpenAI Client
openai_client = OpenAI(api_key=AZURE_API_KEY, base_url=AZURE_ENDPOINT)

# Initialize Azure AI Search Client
search_client = SearchClient(
    endpoint=SEARCH_ENDPOINT,
    index_name=INDEX_NAME,
    credential=AzureKeyCredential(SEARCH_API_KEY),
)

# ==========================================
# 0.1 MOCK INTERNAL EMPLOYEE DATABASE & API
# ==========================================
INTERNAL_EMPLOYEE_DB = {
    "emp001": {
        "employee_id": "EMP001",
        "email": "alice.smith@bank.com",
        "name": "Alice Smith",
        "role": "Senior Backend Developer",
        "past_projects": ["Core Ledger", "Payment Gateway"],
        "current_project": "Payment Gateway V2",
        "days_on_bench": 0,
        "leaves_taken_days": 5
    },
    "emp002": {
        "employee_id": "EMP002",
        "email": "bob.jones@bank.com",
        "name": "Bob Jones",
        "role": "Full-Stack Engineer",
        "past_projects": ["Fraud Detection Service"],
        "current_project": "On Bench",
        "days_on_bench": 14,
        "leaves_taken_days": 2
    },
    "emp003": {
        "employee_id": "EMP003",
        "email": "charlie.brown@bank.com",
        "name": "Charlie Brown",
        "role": "DevOps Engineer",
        "past_projects": ["Infrastructure Migration", "CI/CD Pipeline"],
        "current_project": "Infrastructure Migration",
        "days_on_bench": 0,
        "leaves_taken_days": 8
    },
    "emp004": {
        "employee_id": "EMP004",
        "email": "diana.prince@bank.com",
        "name": "Diana Prince",
        "role": "Security Compliance Lead",
        "past_projects": ["TILA Audit System", "Regulatory Framework"],
        "current_project": "TILA Audit System",
        "days_on_bench": 0,
        "leaves_taken_days": 3
    },
    "emp005": {
        "employee_id": "EMP005",
        "email": "ethan.hunt@bank.com",
        "name": "Ethan Hunt",
        "role": "Java Backend Specialist",
        "past_projects": ["Legacy Core Banking"],
        "current_project": "On Bench",
        "days_on_bench": 28,
        "leaves_taken_days": 1
    },
    "emp006": {
        "employee_id": "EMP006",
        "email": "fiona.gallagher@bank.com",
        "name": "Fiona Gallagher",
        "role": "Frontend React Developer",
        "past_projects": ["Customer Portal", "Mobile Banking UI"],
        "current_project": "Customer Portal",
        "days_on_bench": 0,
        "leaves_taken_days": 4
    },
    "emp007": {
        "employee_id": "EMP007",
        "email": "george.clark@bank.com",
        "name": "George Clark",
        "role": "Data Engineer",
        "past_projects": ["Data Warehouse", "Risk Analytics"],
        "current_project": "Risk Analytics",
        "days_on_bench": 0,
        "leaves_taken_days": 6
    }
}

def query_internal_employee_api(employee_identifier: str):
    key = employee_identifier.strip().lower()
    if key in INTERNAL_EMPLOYEE_DB:
        return {"status": "success", "data": INTERNAL_EMPLOYEE_DB[key]}

    for emp_data in INTERNAL_EMPLOYEE_DB.values():
        if emp_data["email"].lower() == key or emp_data["employee_id"].lower() == key:
            return {"status": "success", "data": emp_data}

    return {"status": "not_found", "message": f"Employee '{employee_identifier}' not found in internal records."}

# ==========================================
# 0.2 LIVE JIRA REST API INTEGRATION
# ==========================================
def query_jira_api(issue_key: str):
    # CRITICAL FIX: Use the REST API endpoint, not /browse/
    url = f"https://{ATLASSIAN_DOMAIN}/rest/api/3/issue/{issue_key.strip().upper()}"
    auth = (ATLASSIAN_EMAIL.strip(), ATLASSIAN_API_TOKEN.strip())

    try:
        with httpx.Client() as client:
            response = client.get(url, auth=auth, timeout=10.0)

            if response.status_code == 200:
                data = response.json()
                fields = data.get("fields", {})
                return {
                    "status": "success",
                    "issue_key": data.get("key"),
                    "summary": fields.get("summary"),
                    "jira_status": fields.get("status", {}).get("name"),
                    "assignee": fields.get("assignee", {}).get("displayName", "Unassigned"),
                    "priority": fields.get("priority", {}).get("name"),
                }
            elif response.status_code == 404:
                return {"status": "not_found", "message": f"Jira ticket '{issue_key}' not found on workspace."}
            else:
                return {"status": "error", "message": f"Jira API error code {response.status_code}: {response.text[:100]}"}
    except Exception as e:
        return {"status": "error", "message": str(e)}

# ==========================================
# 0.3 TOOL DEFINITIONS FOR LLM AGENT
# ==========================================
copilot_tools = [
    {
        "type": "function",
        "function": {
            "name": "fetch_employee_details",
            "description": "Fetch real-time employee profile info including role, past projects, current project, days on bench, and leaves taken using employee ID or email.",
            "parameters": {
                "type": "object",
                "properties": {
                    "employee_identifier": {
                        "type": "string",
                        "description": "The Employee ID (e.g., EMP002) or email address (e.g., bob.jones@bank.com)."
                    }
                },
                "required": ["employee_identifier"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "fetch_jira_ticket_details",
            "description": "Fetch live summary, status, assignee, and priority for a specific Jira issue key (e.g., KAN-1, PROJ-12).",
            "parameters": {
                "type": "object",
                "properties": {
                    "issue_key": {
                        "type": "string",
                        "description": "The exact Jira ticket issue key."
                    }
                },
                "required": ["issue_key"]
            }
        }
    }
]

# ==========================================
# 1. FASTAPI APP & SCHEMA SETUP
# ==========================================
app = FastAPI(title="Enterprise Engineering Knowledge Copilot API")

class QueryRequest(BaseModel):
    question: str

@app.get("/")
def home():
    return {"status": "Enterprise Engineering Knowledge Copilot API is running!"}

# ==========================================
# 2. HYBRID QUERY ENDPOINT
# ==========================================
@app.post("/query")
def run_copilot(req: QueryRequest):
    try:
        user_question = req.question

        # Step 1: Force model to consider tools
        # Step 4: Final Synthesis via gpt-5-mini with strict formatting rules
        response = openai_client.chat.completions.create(
            model=LLM_DEPLOYMENT_NAME,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an expert Enterprise Engineering Knowledge Copilot. "
                        "Format your final response cleanly and concisely using Markdown headings and bullet points. "
                        "Structure your answer into these exact sections: "
                        "1) Executive Summary, 2) Jira Ticket Details, 3) Employee Details, "
                        "4) Compliance & Policy Guidelines, and 5) Sources. "
                        "Keep bullet points short, scannable, and professional."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"User Question: {user_question}\n"
                        f"{tool_context_string}\n\n"
                        f"Vector Policy & Technical Documents:\n{combined_vector_context}"
                    ),
                },
            ],
            temperature=0.5,  # Lower temperature makes formatting more consistent
        )

        response_message = response.choices[0].message
        tool_context_string = ""

        # Step 2: Execute tool calls if the model triggered them
        if response_message.tool_calls:
            print(f"🛠️ Tool calls detected by model: {len(response_message.tool_calls)}")
            for tool_call in response_message.tool_calls:
                function_name = tool_call.function.name
                function_args = json.loads(tool_call.function.arguments)
                print(f"👉 Executing function: {function_name} with args: {function_args}")

                if function_name == "fetch_employee_details":
                    identifier = function_args.get("employee_identifier")
                    api_result = query_internal_employee_api(identifier)
                    tool_context_string += f"\n\nLive Internal API Employee Record:\n{json.dumps(api_result)}"

                elif function_name == "fetch_jira_ticket_details":
                    issue_key = function_args.get("issue_key")
                    api_result = query_jira_api(issue_key)
                    tool_context_string += f"\n\nLive Jira REST API Ticket Data:\n{json.dumps(api_result)}"
        else:
            print("⚠️ No tool calls were triggered by the model for this query.")

        # Step 3: Query Vector Database for RAG Context
        embedding_response = openai_client.embeddings.create(
            input=[user_question], model=EMBEDDING_DEPLOYMENT_NAME, dimensions=1536
        )
        query_vector = embedding_response.data[0].embedding

        vector_query = VectorizedQuery(
            vector=query_vector, k_nearest_neighbors=3, fields="contentVector"
        )

        search_results = search_client.search(
            search_text=None,
            vector_queries=[vector_query],
            select=["source_file", "source_type", "linked_keys", "content"],
        )

        context_snippets = []
        sources_used = []
        for idx, result in enumerate(search_results, start=1):
            sources_used.append({
                "file": result["source_file"],
                "type": result["source_type"],
                "jira_links": result["linked_keys"]
            })
            context_snippets.append(
                f"--- Source [{idx}]: {result['source_file']} ---\n{result['content']}"
            )

        combined_vector_context = "\n\n".join(context_snippets)

        # Step 4: Final Synthesis combining Live Tools + Vector RAG
        final_response = openai_client.chat.completions.create(
            model=LLM_DEPLOYMENT_NAME,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an enterprise knowledge assistant. Answer the user accurately using "
                        "the provided Live API tool results (Employee records / Jira API) and Vector RAG documents. "
                        "Incorporate both seamlessly into your response."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"User Question: {user_question}\n"
                        f"{tool_context_string}\n\n"
                        f"Vector Policy & Technical Documents:\n{combined_vector_context}"
                    ),
                },
            ],
            temperature=0.7,
        )

        return {
            "question": user_question,
            "answer": final_response.choices[0].message.content,
            "sources": sources_used,
            "data_source": "hybrid_apis_and_vector_search" if tool_context_string else "vector_search_only"
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# ==========================================
# 3. RUN SERVER & EXPOSE NGROK TUNNEL
# ==========================================
nest_asyncio.apply()

def run_server():
    uvicorn.run(app, host="0.0.0.0", port=8000)

threading.Thread(target=run_server, daemon=True).start()

ngrok_token = userdata.get("NGROK")
ngrok.set_auth_token(ngrok_token)
public_url = ngrok.connect(8000).public_url

print("\n" + "=" * 60)
print(f"🚀 FastAPI Full-Stack Hybrid Copilot Live!")
print(f"📄 Interactive Swagger Docs: {public_url}/docs")
print(f"🌐 Public API Endpoint:     {public_url}/query")
print("=" * 60)

# Commented out IPython magic to ensure Python compatibility.

# %cd Ragcodebase/

!git status

!git config --global user.email "kunasanipavan@gmail.com"
!git config --global user.name "pavan kunasani"

!git add .
!git commit -m "Update FastAPI implementation"

!git push

import psutil
from pyngrok import ngrok

# 1. Safely kill any process hogging port 8000
killed_count = 0
for proc in psutil.process_iter(['pid', 'name']):
    try:
        for conn in proc.net_connections():
            if conn.laddr.port == 8000:
                proc.kill()
                killed_count += 1
                break
    except (psutil.AccessDenied, psutil.NoSuchProcess, psutil.ZombieProcess, AttributeError):
        pass

print(f"🔪 Terminated {killed_count} process(es) on port 8000.")

# 2. Kill and reset all active ngrok tunnels
try:
    ngrok.kill()
    print("🧹 Successfully disconnected all stale ngrok tunnels.")
except Exception as e:
    print(f"Notice during ngrok cleanup: {e}")

print("✨ Environment is clean! You can now run your main script cell.")