# -*- coding: utf-8 -*-
"""embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NP1b3dPxQwZMx5K9l9KWJ1LbJXNK0bfT
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install openai pandas pypdf azure-search-documents

import os
import pandas as pd
from pypdf import PdfReader
from openai import OpenAI
import psycopg2
from google.colab import userdata

# ==========================================
# 0. CONFIGURATION & CLIENT INITIALIZATION
# ==========================================
EMBEDDING_DEPLOYMENT_NAME = "text-embedding-3-small"

AZURE_API_KEY = userdata.get("AZURE_API_KEY")
AZURE_ENDPOINT = userdata.get("AZURE_ENDPOINT")

# PostgreSQL Connection Secrets from Colab
PG_HOST = userdata.get("PG_HOST")
PG_PORT = userdata.get("PG_PORT", "5432")
PG_DATABASE = userdata.get("PG_DATABASE")
PG_USER = userdata.get("PG_USER")
PG_PASSWORD = userdata.get("PG_PASSWORD")

# Initialize Azure OpenAI Client for Embeddings
openai_client = OpenAI(
    api_key=AZURE_API_KEY,
    base_url=AZURE_ENDPOINT
)

# ==========================================
# 0.1 AUTO-CREATE POSTGRESQL TABLE & VECTOR INDEX
# ==========================================
print("Connecting to PostgreSQL and verifying table schema...")
conn = psycopg2.connect(
    host=PG_HOST,
    port=PG_PORT,
    database=PG_DATABASE,
    user=PG_USER,
    password=PG_PASSWORD
)
cursor = conn.cursor()

# Ensure pgvector extension exists
cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")

# Create documents table with vector(1536) column
cursor.execute("""
CREATE TABLE IF NOT EXISTS enterprise_knowledge (
    chunk_id TEXT PRIMARY KEY,
    content TEXT NOT NULL,
    source_file TEXT,
    source_type TEXT,
    page_number INT,
    linked_keys TEXT[],
    content_vector vector(1536)
);
""")
conn.commit()
print("✅ PostgreSQL table schema ready.")

# ==========================================
# 1. CHUNKING & ENRICHMENT STRATEGY
# ==========================================
def chunk_text(text, chunk_size=350, chunk_overlap=75):
    words = text.split()
    chunks = []
    for i in range(0, len(words), chunk_size - chunk_overlap):
        chunk = " ".join(words[i:i + chunk_size])
        if len(chunk.strip()) > 20:
            chunks.append(chunk)
    return chunks

# ==========================================
# 2. PROCESS JIRA TICKETS (CSV)
# ==========================================
def process_jira_csv(csv_path):
    df = pd.read_csv(csv_path)
    jira_chunks = {}
    file_name = os.path.basename(csv_path)

    for idx, row in df.iterrows():
        issue_key = row.get("Issue Key", f"JIRA-{idx}")
        jira_text = (
            f"[SOURCE TYPE: JIRA_CSV] | Ticket ID: {issue_key}\n"
            f"Status: {row.get('Status', 'Open')} | Assignee: {row.get('Assignee', 'Unassigned')}\n"
            f"Summary: {row.get('Summary', '')}\n"
            f"Description: {row.get('Description', '')}"
        )
        jira_chunks[issue_key] = {
            "chunk_id": f"jira_{issue_key}".lower().replace("-", "_"),
            "content": jira_text,
            "source_file": file_name,
            "source_type": "jira_csv",
            "page_number": 0,
            "linked_keys": [issue_key]
        }
    return jira_chunks

# ==========================================
# 3. PROCESS PDFs WITH CROSS-LINKING
# ==========================================
def process_pdf_with_enrichment(file_path, source_type, known_jira_keys):
    reader = PdfReader(file_path)
    enriched_chunks = []
    file_name = os.path.basename(file_path)

    for page_num, page in enumerate(reader.pages, start=1):
        raw_text = page.extract_text()
        if not raw_text:
            continue
        cleaned_text = " ".join(raw_text.split())

        found_links = [key for key in known_jira_keys if key in cleaned_text]
        text_chunks = chunk_text(cleaned_text, chunk_size=350, chunk_overlap=75)

        for idx, chunk in enumerate(text_chunks):
            link_metadata = f" | Linked Jira Tickets: {', '.join(found_links)}" if found_links else ""
            enriched_content = (
                f"[SOURCE TYPE: {source_type.upper()}] | File: {file_name} | Page: {page_num}{link_metadata}\n"
                f"Content: {chunk}"
            )

            enriched_chunks.append({
                "chunk_id": f"{file_name}_p{page_num}_c{idx}".lower().replace(".", "_").replace(" ", "_"),
                "content": enriched_content,
                "source_file": file_name,
                "source_type": source_type,
                "page_number": page_num,
                "linked_keys": found_links
            })
    return enriched_chunks

# ==========================================
# 4. GENERATE EMBEDDINGS & INSERT INTO POSTGRES
# ==========================================
def generate_and_store_embeddings(master_corpus, dimensions=1536):
    batch_size = 32
    inserted_count = 0

    for i in range(0, len(master_corpus), batch_size):
        batch = master_corpus[i:i + batch_size]
        texts = [item["content"] for item in batch]

        response = openai_client.embeddings.create(
            input=texts,
            model=EMBEDDING_DEPLOYMENT_NAME,
            dimensions=dimensions
        )

        for item, embedding_data in zip(batch, response.data):
            vector_list = embedding_data.embedding # Python list of floats

            cursor.execute("""
                INSERT INTO enterprise_knowledge
                (chunk_id, content, source_file, source_type, page_number, linked_keys, content_vector)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (chunk_id) DO UPDATE SET
                    content = EXCLUDED.content,
                    source_file = EXCLUDED.source_file,
                    source_type = EXCLUDED.source_type,
                    page_number = EXCLUDED.page_number,
                    linked_keys = EXCLUDED.linked_keys,
                    content_vector = EXCLUDED.content_vector;
            """, (
                item["chunk_id"],
                item["content"],
                item["source_file"],
                item["source_type"],
                item["page_number"],
                item["linked_keys"],
                vector_list  # psycopg2-pgvector handles python lists directly if registered or formatted
            ))
            inserted_count += 1

        conn.commit()
    print(f"🎉 Success! Inserted/Updated {inserted_count} records into PostgreSQL.")

# ==========================================
# 5. MAIN EXECUTION PIPELINE
# ==========================================
if __name__ == "__main__":
    jira_csv = "sample_jira_tickets.csv"
    confluence_pdf = "sample_confluence_export.pdf"
    banking_pdf = "sample_banking_knowledge.pdf"

    print("Step 1: Parsing and cross-linking data sources...")
    jira_dict = process_jira_csv(jira_csv)
    valid_keys = list(jira_dict.keys())

    confluence_chunks = process_pdf_with_enrichment(confluence_pdf, "confluence_pdf", valid_keys)
    banking_chunks = process_pdf_with_enrichment(banking_pdf, "banking_pdf", valid_keys)

    master_corpus = list(jira_dict.values()) + confluence_chunks + banking_chunks
    print(f"Total chunks created: {len(master_corpus)}")

    print("Step 2 & 3: Generating text embeddings & uploading to PostgreSQL...")
    generate_and_store_embeddings(master_corpus, dimensions=1536)

    # Clean up connection
    cursor.close()
    conn.close()

import os
import pandas as pd
from pypdf import PdfReader
from openai import OpenAI
from azure.core.credentials import AzureKeyCredential
from azure.search.documents import SearchClient
from google.colab import userdata
# ==========================================
# 0. CREDENTIALS & CLIENT CONFIGURATION
# ==========================================
# Azure AI Foundry (OpenAI) Settings
# os.environ["AZURE_OPENAI_API_KEY"] = "your_azure_openai_api_key_here"
# os.environ["AZURE_OPENAI_ENDPOINT"] = "https://<your-resource-name>.openai.azure.com/openai/v1/"
EMBEDDING_DEPLOYMENT_NAME = "text-embedding-3-small"

# Azure AI Search Settings
SEARCH_ENDPOINT = "https://search-rag-knowledge.search.windows.net"
SEARCH_API_KEY = userdata.get("search_api_key")


AZURE_API_KEY = userdata.get("AZURE_API_KEY")
AZURE_ENDPOINT = userdata.get("AZURE_ENDPOINT")
INDEX_NAME = "enterprise-knowledge-index"

# Initialize Clients
openai_client = OpenAI(
    api_key=AZURE_API_KEY,
    base_url=AZURE_ENDPOINT
)

search_client = SearchClient(
    endpoint=SEARCH_ENDPOINT,
    index_name=INDEX_NAME,
    credential=AzureKeyCredential(SEARCH_API_KEY)
)

# ==========================================
# 1. CHUNKING & ENRICHMENT STRATEGY
# ==========================================
def chunk_text(text, chunk_size=350, chunk_overlap=75):
    """Splits enterprise documentation safely while maintaining context overlap."""
    words = text.split()
    chunks = []
    for i in range(0, len(words), chunk_size - chunk_overlap):
        chunk = " ".join(words[i:i + chunk_size])
        if len(chunk.strip()) > 20:
            chunks.append(chunk)
    return chunks

# ==========================================
# 2. PROCESS JIRA TICKETS (CSV)
# ==========================================
def process_jira_csv(csv_path):
    df = pd.read_csv(csv_path)
    jira_chunks = {}
    file_name = os.path.basename(csv_path)

    for idx, row in df.iterrows():
        issue_key = row.get("Issue Key", f"JIRA-{idx}")
        jira_text = (
            f"[SOURCE TYPE: JIRA_CSV] | Ticket ID: {issue_key}\n"
            f"Status: {row.get('Status', 'Open')} | Assignee: {row.get('Assignee', 'Unassigned')}\n"
            f"Summary: {row.get('Summary', '')}\n"
            f"Description: {row.get('Description', '')}"
        )
        jira_chunks[issue_key] = {
            "chunk_id": f"jira_{issue_key}".lower().replace("-", "_"),
            "content": jira_text,
            "source_file": file_name,
            "source_type": "jira_csv",
            "page_number": 0,
            "linked_keys": [issue_key]
        }
    return jira_chunks

# ==========================================
# 3. PROCESS PDFs (Banking & Confluence) WITH CROSS-LINKING
# ==========================================
def process_pdf_with_enrichment(file_path, source_type, known_jira_keys):
    reader = PdfReader(file_path)
    enriched_chunks = []
    file_name = os.path.basename(file_path)

    for page_num, page in enumerate(reader.pages, start=1):
        raw_text = page.extract_text()
        if not raw_text:
            continue
        cleaned_text = " ".join(raw_text.split())

        # Cross-linking detection: check if any Jira ticket ID appears on this page
        found_links = [key for key in known_jira_keys if key in cleaned_text]
        text_chunks = chunk_text(cleaned_text, chunk_size=350, chunk_overlap=75)

        for idx, chunk in enumerate(text_chunks):
            link_metadata = f" | Linked Jira Tickets: {', '.join(found_links)}" if found_links else ""
            enriched_content = (
                f"[SOURCE TYPE: {source_type.upper()}] | File: {file_name} | Page: {page_num}{link_metadata}\n"
                f"Content: {chunk}"
            )

            enriched_chunks.append({
                "chunk_id": f"{file_name}_p{page_num}_c{idx}".lower().replace(".", "_").replace(" ", "_"),
                "content": enriched_content,
                "source_file": file_name,
                "source_type": source_type,
                "page_number": page_num,
                "linked_keys": found_links
            })
    return enriched_chunks

# ==========================================
# 4. GENERATE EMBEDDINGS VIA AZURE FOUNDRY
# ==========================================
def generate_azure_embeddings(master_corpus, dimensions=1536):
    documents_to_index = []
    batch_size = 32  # Safe batch size constraint

    for i in range(0, len(master_corpus), batch_size):
        batch = master_corpus[i:i + batch_size]
        texts = [item["content"] for item in batch]

        response = openai_client.embeddings.create(
            input=texts,
            model=EMBEDDING_DEPLOYMENT_NAME,
            dimensions=dimensions # Matryoshka dimension reduction (1536, 1024, etc.)
        )

        for item, embedding_data in zip(batch, response.data):
            search_ready_doc = {
                "@search.action": "upload",
                "chunk_id": item["chunk_id"],
                "content": item["content"],
                "source_file": item["source_file"],
                "source_type": item["source_type"],
                "page_number": item["page_number"],
                "linked_keys": item["linked_keys"],
                "contentVector": embedding_data.embedding  # Must map to Azure Search Vector Schema field
            }
            documents_to_index.append(search_ready_doc)

    return documents_to_index

# ==========================================
# 5. MAIN EXECUTION PIPELINE
# ==========================================
if __name__ == "__main__":
    # Your file inputs
    jira_csv = "sample_jira_tickets.csv"
    confluence_pdf = "sample_confluence_export.pdf"
    banking_pdf = "sample_banking_knowledge.pdf"

    print("Step 1: Parsing and cross-linking data sources...")
    jira_dict = process_jira_csv(jira_csv)
    valid_keys = list(jira_dict.keys())

    confluence_chunks = process_pdf_with_enrichment(confluence_pdf, "confluence_pdf", valid_keys)
    banking_chunks = process_pdf_with_enrichment(banking_pdf, "banking_pdf", valid_keys)

    master_corpus = list(jira_dict.values()) + confluence_chunks + banking_chunks
    print(f"Total chunks created: {len(master_corpus)}")

    print("Step 2: Generating text embeddings via Azure AI Foundry...")
    # Tip: Use dimensions=1024 if you want faster indexing speed
    vector_documents = generate_azure_embeddings(master_corpus, dimensions=1536)

    print("Step 3: Uploading vectorized documents to Azure AI Search...")
    upload_result = search_client.upload_documents(documents=vector_documents)

    print(f"🎉 Success! Uploaded {len(vector_documents)} records to Azure AI Search index '{INDEX_NAME}'.")